// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SettleCore.Modules.Payments.Infrastructure.Persistence;

#nullable disable

namespace SettleCore.Modules.Payments.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PaymentsDbContext))]
    [Migration("20261009030228_AddPaymentLedgerPostingAcknowledgmentTime")]
    partial class AddPaymentLedgerPostingAcknowledgmentTime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SettleCore.Modules.Payments.Domain.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ProviderReference", "SettleCore.Modules.Payments.Domain.Payment.ProviderReference#ProviderPaymentReference", b1 =>
                        {
                            b1.Property<string>("Provider")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("provider");

                            b1.Property<string>("Reference")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("provider_payment_reference");
                        });

                    b.HasKey("Id");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("SettleCore.Modules.Payments.Domain.PaymentLedgerPostingIntent", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<long>("FeeAmountMinorUnits")
                        .HasColumnType("bigint")
                        .HasColumnName("fee_amount_minor_units");

                    b.Property<long>("GrossAmountMinorUnits")
                        .HasColumnType("bigint")
                        .HasColumnName("gross_amount_minor_units");

                    b.Property<Guid>("LedgerId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_id");

                    b.Property<Guid>("MerchantPayableAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_payable_account_id");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<Guid>("PlatformRevenueAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("platform_revenue_account_id");

                    b.Property<DateTimeOffset?>("PostedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at");

                    b.Property<Guid>("ProcessorReceivableAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("processor_receivable_account_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.HasKey("PaymentId");

                    b.HasIndex("Status", "NextAttemptAt", "PaymentId")
                        .HasDatabaseName("ix_payment_ledger_posting_intents_due");

                    b.ToTable("payment_ledger_posting_intents", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
