// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SettleCore.Modules.Ledger.Infrastructure.Persistence;

#nullable disable

namespace SettleCore.Modules.Ledger.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LedgerDbContext))]
    [Migration("20260925133602_AddLedgerTransactionsAndEntries")]
    partial class AddLedgerTransactionsAndEntries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SettleCore.Modules.Ledger.Domain.LedgerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("LedgerId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_id");

                    b.HasKey("Id");

                    b.HasIndex("LedgerId")
                        .HasDatabaseName("ix_ledger_accounts_ledger_id");

                    b.ToTable("ledger_accounts", (string)null);
                });

            modelBuilder.Entity("SettleCore.Modules.Ledger.Infrastructure.Persistence.Records.LedgerEntryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<long>("AmountMinorUnits")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_minor_units");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("direction");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_ledger_entries_account_id");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("ix_ledger_entries_transaction_id");

                    b.ToTable("ledger_entries", (string)null);
                });

            modelBuilder.Entity("SettleCore.Modules.Ledger.Infrastructure.Persistence.Records.LedgerTransactionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("LedgerId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_id");

                    b.HasKey("Id");

                    b.HasIndex("LedgerId")
                        .HasDatabaseName("ix_ledger_transactions_ledger_id");

                    b.ToTable("ledger_transactions", (string)null);
                });

            modelBuilder.Entity("SettleCore.Modules.Ledger.Infrastructure.Persistence.Records.LedgerEntryRecord", b =>
                {
                    b.HasOne("SettleCore.Modules.Ledger.Domain.LedgerAccount", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SettleCore.Modules.Ledger.Infrastructure.Persistence.Records.LedgerTransactionRecord", null)
                        .WithMany("Entries")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SettleCore.Modules.Ledger.Infrastructure.Persistence.Records.LedgerTransactionRecord", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
